sonar.organization=library-management-project
sonar.projectKey=stanko-dev_library-management-system
sonar.projectName=Library Management System
sonar.python.version=3.12
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
sonar.coverage.exclusions=tests/,**/__init__.py
