class LibraryError(Exception):
    """Root for all domain errors — catch this to handle any library fault."""


class ReaderNotFoundError(LibraryError): ...
class BookNotFoundError(LibraryError): ...
class LoanNotFoundError(LibraryError): ...
class ReservationNotFoundError(LibraryError): ...
class ReaderBlockedError(LibraryError): ...
class BookNotAvailableError(LibraryError): ...
class LoanLimitExceededError(LibraryError): ...
class AlreadyReturnedError(LibraryError): ...
class DuplicateReservationError(LibraryError): ...
