class ProjectSystemError(Exception):
    """Root for all domain errors."""


class StudentNotFoundError(ProjectSystemError): ...
class TeamNotFoundError(ProjectSystemError): ...
class ProjectNotFoundError(ProjectSystemError): ...
class MilestoneNotFoundError(ProjectSystemError): ...
class SubmissionNotFoundError(ProjectSystemError): ...
class StudentBlockedError(ProjectSystemError): ...
class TeamFullError(ProjectSystemError): ...
class DuplicateQueueRequestError(ProjectSystemError): ...
class InvalidStatusTransitionError(ProjectSystemError): ...
class AlreadySubmittedError(ProjectSystemError): ...
class StudentNotInTeamError(ProjectSystemError): ...
